<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            ['code' => '001', 'name' => 'BANXICO'],
            ['code' => '002', 'name' => 'BANAMEX'],
            ['code' => '006', 'name' => 'BANCOMEXT'],
            ['code' => '009', 'name' => 'BANOBRAS'],
            ['code' => '012', 'name' => 'BBVA'],
            ['code' => '014', 'name' => 'SANTANDER'],
            ['code' => '019', 'name' => 'BANJERCITO'],
            ['code' => '021', 'name' => 'HSBC'],
            ['code' => '022', 'name' => 'GE MONEY'],
            ['code' => '030', 'name' => 'BAJIO'],
            ['code' => '032', 'name' => 'IXE'],
            ['code' => '036', 'name' => 'INBURSA'],
            ['code' => '037', 'name' => 'INTERACCIONES'],
            ['code' => '042', 'name' => 'MIFEL'],
            ['code' => '044', 'name' => 'SCOTIABANK'],
            ['code' => '058', 'name' => 'BANREGIO'],
            ['code' => '059', 'name' => 'INVEX'],
            ['code' => '060', 'name' => 'BANSI'],
            ['code' => '062', 'name' => 'AFIRME'],
            ['code' => '072', 'name' => 'BANORTE'],
            ['code' => '102', 'name' => 'ACCENDO BANCO'],
            ['code' => '103', 'name' => 'AMERICAN EXPRESS'],
            ['code' => '106', 'name' => 'BANK OF AMERICA'],
            ['code' => '108', 'name' => 'TOKYO'],
            ['code' => '110', 'name' => 'JP MORGAN'],
            ['code' => '112', 'name' => 'MONEX'],
            ['code' => '113', 'name' => 'VE POR MAS'],
            ['code' => '116', 'name' => 'ING'],
            ['code' => '124', 'name' => 'CITI'],
            ['code' => '126', 'name' => 'CREDIT SUISSE'],
            ['code' => '127', 'name' => 'BANCO AZTECA'],
            ['code' => '128', 'name' => 'AUTOFIN'],
            ['code' => '129', 'name' => 'BARCLAYS'],
            ['code' => '130', 'name' => 'COMPARTAMOS'],
            ['code' => '131', 'name' => 'FAMSA'],
            ['code' => '132', 'name' => 'MULTIVA'],
            ['code' => '133', 'name' => 'ACTINVER'],
            ['code' => '134', 'name' => 'WAL-MART'],
            ['code' => '135', 'name' => 'NAFIN'],
            ['code' => '136', 'name' => 'INTERBANCO'],
            ['code' => '137', 'name' => 'BANCOPPEL'],
            ['code' => '138', 'name' => 'ABC CAPITAL'],
            ['code' => '139', 'name' => 'UBS BANK'],
            ['code' => '140', 'name' => 'CONSUBANCO'],
            ['code' => '141', 'name' => 'VOLKSWAGEN'],
            ['code' => '143', 'name' => 'CIBANCO'],
            ['code' => '145', 'name' => 'BBASE'],
            ['code' => '147', 'name' => 'BANKAOOL'],
            ['code' => '148', 'name' => 'PAGATODO'],
            ['code' => '150', 'name' => 'BIM (INMOBILIARIO)'],
            ['code' => '151', 'name' => 'DONDE'],
            ['code' => '152', 'name' => 'BANCREA'],
            ['code' => '154', 'name' => 'BANCO FINTERRA'],
            ['code' => '155', 'name' => 'ICBC'],
            ['code' => '156', 'name' => 'SABADELL'],
            ['code' => '157', 'name' => 'SHINHAN'],
            ['code' => '158', 'name' => 'MIZUHO BANK'],
            ['code' => '159', 'name' => 'BANK OF CHINA'],
            ['code' => '160', 'name' => 'BANCO S3'],
            ['code' => '166', 'name' => 'BANSEFI / BIENESTAR'],
            ['code' => '167', 'name' => 'HEY BANCO'],
            ['code' => '168', 'name' => 'HIPOTECARIA FEDERAL'],
            ['code' => '600', 'name' => 'MONEXCB'],
            ['code' => '601', 'name' => 'GBM'],
            ['code' => '602', 'name' => 'MASARI'],
            ['code' => '604', 'name' => 'C.B. INBURSA'],
            ['code' => '605', 'name' => 'VALUE'],
            ['code' => '606', 'name' => 'ESTRUCTURADORES'],
            ['code' => '607', 'name' => 'TIBER'],
            ['code' => '608', 'name' => 'VECTOR'],
            ['code' => '610', 'name' => 'B&B'],
            ['code' => '611', 'name' => 'INTERCAM'],
            ['code' => '613', 'name' => 'MULTIVA CB'],
            ['code' => '614', 'name' => 'ACCIVAL'],
            ['code' => '615', 'name' => 'MERRILL LYNCH'],
            ['code' => '616', 'name' => 'FINAMEX'],
            ['code' => '617', 'name' => 'VALMEX'],
            ['code' => '618', 'name' => 'ÚNICA Casa de Cambio'],
            ['code' => '619', 'name' => 'ASEGURADORA MAPFRE'],
            ['code' => '620', 'name' => 'PROFUTURO'],
            ['code' => '621', 'name' => 'CB ACTINVER'],
            ['code' => '622', 'name' => 'ACTINVE SI'],
            ['code' => '623', 'name' => 'SKANDIA'],
            ['code' => '624', 'name' => 'CONSULTORÍA CB'],
            ['code' => '626', 'name' => 'CB DEUTSCHE'],
            ['code' => '627', 'name' => 'ZURICH'],
            ['code' => '628', 'name' => 'ZURICH VIDA'],
            ['code' => '629', 'name' => 'HIPOTECARIA SU CASITA'],
            ['code' => '630', 'name' => 'CB INTERCAM'],
            ['code' => '631', 'name' => 'CI BOLSA'],
            ['code' => '632', 'name' => 'BULLTICK C.B.'],
            ['code' => '633', 'name' => 'STERLING'],
            ['code' => '634', 'name' => 'FINCOMUN'],
            ['code' => '636', 'name' => 'HDI SEGUROS'],
            ['code' => '637', 'name' => 'ORDER EXPRESS'],
            ['code' => '638', 'name' => 'AKALA'],
            ['code' => '640', 'name' => 'J.P. MORGAN CB'],
            ['code' => '642', 'name' => 'CB J.P. MORGAN'],
            ['code' => '646', 'name' => 'STP (Sistema de Transferencias y Pagos)'],
            ['code' => '649', 'name' => 'SPIN BY OXXO (COMPROPAGO)'],
            ['code' => '702', 'name' => 'INDEVAL'],
            ['code' => '710', 'name' => 'CB BANORTE'],
        ];

        foreach ($banks as $bank) {
            Bank::updateOrCreate(['code' => $bank['code']], ['name' => $bank['name'], 'enabled' => true]);
        }
    }
}
